create database grocerystore
CREATE TABLE USER(
USER_ID INTEGER NOT NULL AUTO_iNCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME  VARCHAR(50),
EMAIL VARCHAR(50),
STORE_NAME VARCHAR(50),
USER_TYPE  VARCHAR(50),
USER_NAME VARCHAR(50),
PHONE_NUMBER VARCHAR(50),
PASSWORD VARCHAR(50),
DATE_OF_REGISTRATION DATE 
);

CREATE TABLE GROCERY(
GROCERY_ID INTEGER NOT NULL AUTO_iNCREMENT PRIMARY KEY,
GROCERY_NAME VARCHAR(50),
GROCERY_COST  DOUBLE,
GROCERY_QUANTITY INTEGER,
USER_ID INTEGER
);

CREATE TABLE ORDERS(
ORDER_ID INTEGER NOT NULL AUTO_iNCREMENT PRIMARY KEY,
ORDER_STATUS VARCHAR(50),
TOTAL_COST  DOUBLE,
USER_ID INTEGER
);

CREATE TABLE ORDER_DETAILS(
ORDER_DETAILS_ID INTEGER NOT NULL AUTO_iNCREMENT PRIMARY KEY,
QUANTITY Integer,
GROCERY_ID Integer,
COST  DOUBLE,
USER_ID INTEGER,
ORDER_ID Integer
);




